controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|POST

# app_static_page:
#     path: /static/page
#     controller: App\Controller\StaticPageController::index

app_mentions:
    path: /mentions
    controller: App\Controller\StaticPageController::mentionsLegales
    methods: GET

app_politique:
    path: /confidentialite
    controller: App\Controller\StaticPageController::politiqueCookies
    methods: GET